const actionTypes = {
    GET_PERSONS_START: 'GET_PERSONS_START',
    GET_PERSONS: 'GET_PERSONS',
    SET_PERSONS: 'SET_PERSONS',
    GET_DATAS_START: 'GET_DATAS_START',
    GET_DATAS: 'GET_DATAS',
    SET_DATAS: 'SET_DATAS',
    SET_FILTERED_DATAS: 'SET_FILTERED_DATAS',
    ERROR: 'ERROR'
}

export default actionTypes;